# Generated by Django 4.2.13 on 2024-06-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="account",
            table="account",
        ),
        migrations.AlterModelTable(
            name="accountlogintype",
            table="account_login_type",
        ),
        migrations.AlterModelTable(
            name="accountroletype",
            table="account_role_type",
        ),
        migrations.AlterModelTable(
            name="profile",
            table="profile",
        ),
    ]
