# Generated by Django 4.2.13 on 2024-06-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_account_table_alter_accountlogintype_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="account",
            name="last_login_date",
        ),
    ]
