# Generated by Django 4.2.13 on 2024-06-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_account_create_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="password",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profile_image_name",
        ),
    ]
