# Generated by Django 4.2.13 on 2024-06-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_profile_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="login_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account.accountlogintype",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="role_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account.accountroletype",
            ),
        ),
    ]
