# Generated by Django 4.2.13 on 2024-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_account_login_type_alter_account_role_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
